name: flutter_geocoder_reborn
description: A geocoding plugin
version: 0.0.4
homepage: None

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pavelclaudiustefan.flutter_geocoder_reborn
        pluginClass: FlutterGeocoderRebornPlugin
      ios:
        pluginClass: FlutterGeocoderRebornPlugin
